//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoe_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string OrdersArticle { get; set; }
        public System.DateTime OrdersDate { get; set; }
        public System.DateTime DeliverisDate { get; set; }
        public int PointAddressID { get; set; }
        public int UserID { get; set; }
        public int Code { get; set; }
        public int StatusID { get; set; }
    
        public virtual PointAddress PointAddress { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
